---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Krzych.
--- DateTime: 27/06/2024 15:40
---

API = {}
function API.move(request)
    return true, request .. "AA"
end

function API.init(request)
    return request .. "frominit"
end

function API.query(request)
    return false, "query: " .. request
end